---
version: '3.4'
services:
  php:
    container_name: hockey-php
    build:
      context: ./php
    volumes:
      - ./rekreacni-hokej:/var/vhost/app
  apache:
    container_name: hockey-apache
    build:
      context: ./apache
    volumes:
      - ./rekreacni-hokej:/var/vhost/app
    ports:
      - "8081:80"
  mysql:
    container_name: hockey-mysql
    image: mariadb
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
