---
version: '3.4'
services:
  php:
    container_name: hockey-php
    build:
      network: host
      context: ./php
    volumes:
      - ./rekreacni-hokej:/var/vhost/app
    ports:
      - "8080:8080"
  mysql:
    container_name: hockey-mysql
    image: mariadb
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
